"""thêm otp verify để có thể gửi mail xác thực otp quên mật khẩu

Revision ID: 0bc94f59b968
Revises: a7c9e1f3b520
Create Date: 2026-08-08 14:56:55.761055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bc94f59b968'
down_revision: Union[str, Sequence[str], None] = 'a7c9e1f3b520'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('otp_verifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('old_password_hash', sa.Text(), nullable=False),
    sa.Column('new_password_hash', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='auth'
    )
    op.create_index(op.f('ix_auth_otp_verifications_user_id'), 'otp_verifications', ['user_id'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_auth_otp_verifications_user_id'), table_name='otp_verifications', schema='auth')
    op.drop_table('otp_verifications', schema='auth')
    # ### end Alembic commands ###
