"""thêm các table liên quan đến notification filebase

Revision ID: 25d41538d3f0
Revises: 6b7f9c2d4e10
Create Date: 2026-06-25 23:07:05.218519

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25d41538d3f0'
down_revision: Union[str, Sequence[str], None] = '6b7f9c2d4e10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_refresh_tokens_expires'), table_name='refresh_tokens', schema='auth')
    op.drop_index(op.f('idx_refresh_tokens_user_id'), table_name='refresh_tokens', schema='auth')
    op.drop_table_comment(
        'refresh_tokens',
        existing_comment='Refresh token store for JWT-based authentication.',
        schema='auth'
    )
    op.drop_table_comment(
        'roles',
        existing_comment='RBAC roles for RDMS users.',
        schema='auth'
    )
    op.drop_index(op.f('idx_users_department_id'), table_name='users', schema='auth')
    op.drop_index(op.f('idx_users_role_id'), table_name='users', schema='auth')
    op.drop_index(op.f('idx_users_status'), table_name='users', schema='auth')
    op.drop_index(op.f('uq_users_email_active'), table_name='users', schema='auth', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('uq_users_username_active'), table_name='users', schema='auth', postgresql_where='(deleted_at IS NULL)')
    op.drop_table_comment(
        'users',
        existing_comment='RDMS user accounts. Passwords must be stored as hashes only.',
        schema='auth'
    )
    op.drop_index(op.f('idx_core_files_research_id'), table_name='file_attachments', schema='core')
    op.drop_index(op.f('idx_metadata_versions_research_id'), table_name='metadata_versions', schema='core')
    op.drop_table_comment(
        'metadata_versions',
        existing_comment='Metadata snapshots for versioning and traceability.',
        schema='core'
    )
    op.drop_index(op.f('idx_core_authors_research_id'), table_name='research_object_authors', schema='core')
    op.drop_index(op.f('idx_core_access_level'), table_name='research_objects', schema='core')
    op.drop_index(op.f('idx_core_approved_at'), table_name='research_objects', schema='core')
    op.drop_index(op.f('idx_core_department'), table_name='research_objects', schema='core')
    op.drop_index(op.f('idx_core_output_type'), table_name='research_objects', schema='core')
    op.drop_index(op.f('idx_core_research_fts'), table_name='research_objects', schema='core', postgresql_using='gin')
    op.drop_index(op.f('idx_core_year'), table_name='research_objects', schema='core')
    op.drop_index(op.f('uq_core_identifier_active'), table_name='research_objects', schema='core', postgresql_where='((identifier IS NOT NULL) AND (deleted_at IS NULL))')
    op.drop_table_comment(
        'research_objects',
        existing_comment='Approved official research metadata records.',
        schema='core'
    )
    op.drop_index(op.f('idx_audit_action_code'), table_name='audit_logs', schema='log')
    op.drop_index(op.f('idx_audit_actor'), table_name='audit_logs', schema='log')
    op.drop_index(op.f('idx_audit_created_at'), table_name='audit_logs', schema='log')
    op.drop_index(op.f('idx_audit_target'), table_name='audit_logs', schema='log')
    op.drop_table_comment(
        'audit_logs',
        existing_comment='Audit trail for important system and data changes.',
        schema='log'
    )
    op.drop_index(op.f('idx_login_logs_created_at'), table_name='login_logs', schema='log')
    op.drop_index(op.f('idx_login_logs_result'), table_name='login_logs', schema='log')
    op.drop_index(op.f('idx_login_logs_user_id'), table_name='login_logs', schema='log')
    op.drop_table_comment(
        'login_logs',
        existing_comment='Login success/failure records.',
        schema='log'
    )
    op.drop_index(op.f('idx_workflow_performed_at'), table_name='workflow_history', schema='log')
    op.drop_index(op.f('idx_workflow_performed_by'), table_name='workflow_history', schema='log')
    op.drop_index(op.f('idx_workflow_research_id'), table_name='workflow_history', schema='log')
    op.drop_index(op.f('idx_workflow_staging_id'), table_name='workflow_history', schema='log')
    op.drop_table_comment(
        'workflow_history',
        existing_comment='Workflow transition history for review and approval process.',
        schema='log'
    )
    op.drop_index(op.f('idx_departments_parent'), table_name='departments', schema='reference')
    op.drop_table_comment(
        'departments',
        existing_comment='University units such as faculty, department, center, office.',
        schema='reference'
    )
    op.drop_index(op.f('idx_keywords_text'), table_name='keywords', schema='reference')
    op.drop_table_comment(
        'keywords',
        existing_comment='Controlled or semi-controlled keywords for research metadata.',
        schema='reference'
    )
    op.drop_table_comment(
        'output_types',
        existing_comment='Research object types such as project, publication, dataset, evidence document.',
        schema='reference'
    )
    op.drop_index(op.f('idx_domains_parent'), table_name='research_domains', schema='reference')
    op.drop_table_comment(
        'research_domains',
        existing_comment='Research domains used for classification and reporting.',
        schema='reference'
    )
    op.drop_index(op.f('idx_researchers_department_id'), table_name='researchers', schema='reference')
    op.drop_index(op.f('idx_researchers_full_name'), table_name='researchers', schema='reference')
    op.drop_table_comment(
        'researchers',
        existing_comment='Researchers, lecturers, students or external contributors.',
        schema='reference'
    )
    op.drop_index(op.f('idx_staging_files_staging_id'), table_name='file_attachments', schema='staging')
    op.drop_table_comment(
        'file_attachments',
        existing_comment='Attachment metadata for staging research objects. Physical files are stored outside the database.',
        schema='staging'
    )
    op.drop_index(op.f('idx_staging_authors_staging_id'), table_name='research_object_authors', schema='staging')
    op.drop_index(op.f('idx_staging_created_by'), table_name='research_objects', schema='staging')
    op.drop_index(op.f('idx_staging_department'), table_name='research_objects', schema='staging')
    op.drop_index(op.f('idx_staging_output_type'), table_name='research_objects', schema='staging')
    op.drop_index(op.f('idx_staging_status'), table_name='research_objects', schema='staging')
    op.drop_index(op.f('idx_staging_year'), table_name='research_objects', schema='staging')
    op.drop_table_comment(
        'research_objects',
        existing_comment='Temporary research metadata records before formal approval.',
        schema='staging'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'research_objects',
        'Temporary research metadata records before formal approval.',
        existing_comment=None,
        schema='staging'
    )
    op.create_index(op.f('idx_staging_year'), 'research_objects', ['year'], unique=False, schema='staging')
    op.create_index(op.f('idx_staging_status'), 'research_objects', ['workflow_status'], unique=False, schema='staging')
    op.create_index(op.f('idx_staging_output_type'), 'research_objects', ['output_type_id'], unique=False, schema='staging')
    op.create_index(op.f('idx_staging_department'), 'research_objects', ['department_id'], unique=False, schema='staging')
    op.create_index(op.f('idx_staging_created_by'), 'research_objects', ['created_by'], unique=False, schema='staging')
    op.create_index(op.f('idx_staging_authors_staging_id'), 'research_object_authors', ['staging_id'], unique=False, schema='staging')
    op.create_table_comment(
        'file_attachments',
        'Attachment metadata for staging research objects. Physical files are stored outside the database.',
        existing_comment=None,
        schema='staging'
    )
    op.create_index(op.f('idx_staging_files_staging_id'), 'file_attachments', ['staging_id'], unique=False, schema='staging')
    op.create_table_comment(
        'researchers',
        'Researchers, lecturers, students or external contributors.',
        existing_comment=None,
        schema='reference'
    )
    op.create_index(op.f('idx_researchers_full_name'), 'researchers', ['full_name'], unique=False, schema='reference')
    op.create_index(op.f('idx_researchers_department_id'), 'researchers', ['department_id'], unique=False, schema='reference')
    op.create_table_comment(
        'research_domains',
        'Research domains used for classification and reporting.',
        existing_comment=None,
        schema='reference'
    )
    op.create_index(op.f('idx_domains_parent'), 'research_domains', ['parent_domain_id'], unique=False, schema='reference')
    op.create_table_comment(
        'output_types',
        'Research object types such as project, publication, dataset, evidence document.',
        existing_comment=None,
        schema='reference'
    )
    op.create_table_comment(
        'keywords',
        'Controlled or semi-controlled keywords for research metadata.',
        existing_comment=None,
        schema='reference'
    )
    op.create_index(op.f('idx_keywords_text'), 'keywords', ['keyword_text'], unique=False, schema='reference')
    op.create_table_comment(
        'departments',
        'University units such as faculty, department, center, office.',
        existing_comment=None,
        schema='reference'
    )
    op.create_index(op.f('idx_departments_parent'), 'departments', ['parent_department_id'], unique=False, schema='reference')
    op.create_table_comment(
        'workflow_history',
        'Workflow transition history for review and approval process.',
        existing_comment=None,
        schema='log'
    )
    op.create_index(op.f('idx_workflow_staging_id'), 'workflow_history', ['staging_id'], unique=False, schema='log')
    op.create_index(op.f('idx_workflow_research_id'), 'workflow_history', ['research_id'], unique=False, schema='log')
    op.create_index(op.f('idx_workflow_performed_by'), 'workflow_history', ['performed_by'], unique=False, schema='log')
    op.create_index(op.f('idx_workflow_performed_at'), 'workflow_history', ['performed_at'], unique=False, schema='log')
    op.create_table_comment(
        'login_logs',
        'Login success/failure records.',
        existing_comment=None,
        schema='log'
    )
    op.create_index(op.f('idx_login_logs_user_id'), 'login_logs', ['user_id'], unique=False, schema='log')
    op.create_index(op.f('idx_login_logs_result'), 'login_logs', ['login_result'], unique=False, schema='log')
    op.create_index(op.f('idx_login_logs_created_at'), 'login_logs', ['created_at'], unique=False, schema='log')
    op.create_table_comment(
        'audit_logs',
        'Audit trail for important system and data changes.',
        existing_comment=None,
        schema='log'
    )
    op.create_index(op.f('idx_audit_target'), 'audit_logs', ['target_schema', 'target_table', 'target_id'], unique=False, schema='log')
    op.create_index(op.f('idx_audit_created_at'), 'audit_logs', ['created_at'], unique=False, schema='log')
    op.create_index(op.f('idx_audit_actor'), 'audit_logs', ['actor_user_id'], unique=False, schema='log')
    op.create_index(op.f('idx_audit_action_code'), 'audit_logs', ['action_code'], unique=False, schema='log')
    op.create_table_comment(
        'research_objects',
        'Approved official research metadata records.',
        existing_comment=None,
        schema='core'
    )
    op.create_index(op.f('uq_core_identifier_active'), 'research_objects', [sa.literal_column('lower(identifier::text)')], unique=True, schema='core', postgresql_where='((identifier IS NOT NULL) AND (deleted_at IS NULL))')
    op.create_index(op.f('idx_core_year'), 'research_objects', ['year'], unique=False, schema='core')
    op.create_index(op.f('idx_core_research_fts'), 'research_objects', ['search_vector'], unique=False, schema='core', postgresql_using='gin')
    op.create_index(op.f('idx_core_output_type'), 'research_objects', ['output_type_id'], unique=False, schema='core')
    op.create_index(op.f('idx_core_department'), 'research_objects', ['department_id'], unique=False, schema='core')
    op.create_index(op.f('idx_core_approved_at'), 'research_objects', ['approved_at'], unique=False, schema='core')
    op.create_index(op.f('idx_core_access_level'), 'research_objects', ['access_level'], unique=False, schema='core')
    op.create_index(op.f('idx_core_authors_research_id'), 'research_object_authors', ['research_id'], unique=False, schema='core')
    op.create_table_comment(
        'metadata_versions',
        'Metadata snapshots for versioning and traceability.',
        existing_comment=None,
        schema='core'
    )
    op.create_index(op.f('idx_metadata_versions_research_id'), 'metadata_versions', ['research_id'], unique=False, schema='core')
    op.create_index(op.f('idx_core_files_research_id'), 'file_attachments', ['research_id'], unique=False, schema='core')
    op.create_table_comment(
        'users',
        'RDMS user accounts. Passwords must be stored as hashes only.',
        existing_comment=None,
        schema='auth'
    )
    op.create_index(op.f('uq_users_username_active'), 'users', ['username'], unique=True, schema='auth', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('uq_users_email_active'), 'users', ['email'], unique=True, schema='auth', postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('idx_users_status'), 'users', ['status'], unique=False, schema='auth')
    op.create_index(op.f('idx_users_role_id'), 'users', ['role_id'], unique=False, schema='auth')
    op.create_index(op.f('idx_users_department_id'), 'users', ['department_id'], unique=False, schema='auth')
    op.create_table_comment(
        'roles',
        'RBAC roles for RDMS users.',
        existing_comment=None,
        schema='auth'
    )
    op.create_table_comment(
        'refresh_tokens',
        'Refresh token store for JWT-based authentication.',
        existing_comment=None,
        schema='auth'
    )
    op.create_index(op.f('idx_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False, schema='auth')
    op.create_index(op.f('idx_refresh_tokens_expires'), 'refresh_tokens', ['expires_at'], unique=False, schema='auth')
    # ### end Alembic commands ###
