"""init database

Revision ID: 2c9ebd1eb073
Revises: 
Create Date: 2026-04-27 20:25:31.870983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2c9ebd1eb073'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('author_code', sa.String(length=12), nullable=False),
    sa.Column('author_type', sa.SmallInteger(), nullable=False),
    sa.Column('education_level', sa.SmallInteger(), nullable=False),
    sa.Column('department_id', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_code'),
    sa.UniqueConstraint('email')
    )
    op.create_table('researches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_code', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.Date(), nullable=False),
    sa.Column('version', sa.String(length=3), nullable=False),
    sa.Column('department_id', sa.SmallInteger(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('research_code'),
    sa.UniqueConstraint('title')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('user_code', sa.String(length=15), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=False),
    sa.Column('update_at', sa.Date(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_code')
    )
    op.create_table('files',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_code', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=20), nullable=False),
    sa.Column('file_type', sa.SmallInteger(), nullable=False),
    sa.Column('file_size', sa.Float(), nullable=False),
    sa.Column('upload_by', sa.String(length=36), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['research_code'], ['researches.research_code'], ),
    sa.ForeignKeyConstraint(['upload_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keywords',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('research_code', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['research_code'], ['researches.research_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('research_author',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('research_code', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['research_code'], ['researches.research_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('research_author')
    op.drop_table('keywords')
    op.drop_table('files')
    op.drop_table('users')
    op.drop_table('researches')
    op.drop_table('authors')
    op.drop_table('roles')
    op.drop_table('departments')
    # ### end Alembic commands ###
