"""add is_read to notifications

Revision ID: a1ab58ebe3b6
Revises: e040c3f7a072
Create Date: 2026-06-26 19:14:49.490655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ab58ebe3b6'
down_revision: Union[str, Sequence[str], None] = 'e040c3f7a072'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notifications', sa.Column('is_read', sa.Boolean(), server_default=sa.text('false'), nullable=False), schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notifications', 'is_read', schema='reference')
    # ### end Alembic commands ###
