"""init all schemas

Revision ID: bc84167c6a36
Revises: 
Create Date: 2026-05-20 02:42:48.984176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc84167c6a36'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='public'
    )
    op.create_table('authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('author_code', sa.String(length=12), nullable=False),
    sa.Column('author_type', sa.SmallInteger(), nullable=False),
    sa.Column('education_level', sa.SmallInteger(), nullable=False),
    sa.Column('department_id', sa.SmallInteger(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['public.departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_code'),
    sa.UniqueConstraint('email'),
    schema='public'
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('user_code', sa.String(length=15), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('department_id', sa.SmallInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['public.departments.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['public.roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('user_code'),
    schema='public'
    )
    op.create_index('idx_users_active_email', 'users', ['email'], unique=False, schema='public', postgresql_where='is_deleted = FALSE')
    op.create_index('idx_users_role', 'users', ['role_id'], unique=False, schema='public', postgresql_where='is_deleted = FALSE')
    op.create_table('core_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('stg_project_id', sa.String(length=36), nullable=False),
    sa.Column('stg_version_number', sa.Integer(), nullable=False),
    sa.Column('identifier', sa.String(length=30), nullable=False),
    sa.Column('approved_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('dc_title', sa.String(length=500), nullable=False),
    sa.Column('dc_creator', sa.String(length=500), nullable=False),
    sa.Column('dc_description', sa.Text(), nullable=True),
    sa.Column('dc_date', sa.String(length=20), nullable=True),
    sa.Column('dc_type', sa.SmallInteger(), nullable=False),
    sa.Column('dc_language', sa.SmallInteger(), nullable=False),
    sa.Column('dc_publisher', sa.String(length=255), nullable=True),
    sa.Column('dc_contributor', sa.Text(), nullable=True),
    sa.Column('dc_subject', sa.Text(), nullable=True),
    sa.Column('dc_relation', sa.String(length=500), nullable=True),
    sa.Column('dc_coverage', sa.String(length=255), nullable=True),
    sa.Column('dc_rights', sa.SmallInteger(), nullable=False),
    sa.Column('dc_source', sa.String(length=500), nullable=True),
    sa.Column('dc_format', sa.String(length=100), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('approved_by', sa.String(length=36), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_edited_by', sa.String(length=36), nullable=True),
    sa.Column('last_edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('edit_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.CheckConstraint('edit_count = 0 OR last_edited_at IS NOT NULL', name='chk_core_edit_tracking'),
    sa.ForeignKeyConstraint(['approved_by'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['last_edited_by'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier'),
    schema='core'
    )
    op.create_index('idx_core_approved_at', 'core_projects', ['approved_at'], unique=False, schema='core')
    op.create_index('idx_core_fts', 'core_projects', ['search_vector'], unique=False, schema='core', postgresql_using='gin', postgresql_where='status = 1')
    op.create_index('idx_core_snapshot', 'core_projects', ['approved_snapshot'], unique=False, schema='core', postgresql_using='gin')
    op.create_index('idx_core_status', 'core_projects', ['status'], unique=False, schema='core')
    op.create_index('idx_core_stg_id', 'core_projects', ['stg_project_id'], unique=False, schema='core')
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='log'
    )
    op.create_index('idx_audit_created_at', 'audit_logs', ['created_at'], unique=False, schema='log')
    op.create_index('idx_audit_entity', 'audit_logs', ['entity_type', 'entity_id'], unique=False, schema='log')
    op.create_index('idx_audit_user', 'audit_logs', ['user_id'], unique=False, schema='log')
    op.create_table('login_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('email_attempted', sa.String(length=320), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('failure_reason', sa.String(length=100), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    schema='log'
    )
    op.create_index('idx_login_created_at', 'login_logs', ['created_at'], unique=False, schema='log')
    op.create_index('idx_login_user', 'login_logs', ['user_id'], unique=False, schema='log')
    op.create_table('refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['public.users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token'),
    schema='public'
    )
    op.create_index('idx_refresh_tokens_active', 'refresh_tokens', ['token'], unique=False, schema='public', postgresql_where='revoked_at IS NULL')
    op.create_table('stg_projects',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('identifier', sa.String(length=30), nullable=False),
    sa.Column('owner_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('dc_title', sa.String(length=500), nullable=False),
    sa.Column('dc_creator', sa.String(length=500), nullable=False),
    sa.Column('dc_description', sa.Text(), nullable=True),
    sa.Column('dc_date', sa.String(length=20), nullable=True),
    sa.Column('dc_type', sa.SmallInteger(), nullable=False),
    sa.Column('dc_language', sa.SmallInteger(), nullable=False),
    sa.Column('dc_publisher', sa.String(length=255), nullable=True),
    sa.Column('dc_contributor', sa.Text(), nullable=True),
    sa.Column('dc_subject', sa.Text(), nullable=True),
    sa.Column('dc_relation', sa.String(length=500), nullable=True),
    sa.Column('dc_coverage', sa.String(length=255), nullable=True),
    sa.Column('dc_rights', sa.SmallInteger(), nullable=False),
    sa.Column('dc_source', sa.String(length=500), nullable=True),
    sa.Column('dc_format', sa.String(length=100), nullable=True),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('core_project_id', sa.String(length=36), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=36), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.CheckConstraint('is_deleted = FALSE OR deleted_at IS NOT NULL', name='chk_stg_deleted_at'),
    sa.CheckConstraint('status = 1 OR submitted_at IS NOT NULL', name='chk_stg_submitted_at'),
    sa.ForeignKeyConstraint(['owner_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identifier'),
    schema='staging'
    )
    op.create_index('idx_stg_fts', 'stg_projects', ['search_vector'], unique=False, schema='staging', postgresql_using='gin')
    op.create_index('idx_stg_identifier', 'stg_projects', ['identifier'], unique=False, schema='staging')
    op.create_index('idx_stg_owner', 'stg_projects', ['owner_id'], unique=False, schema='staging', postgresql_where='is_deleted = FALSE')
    op.create_index('idx_stg_status', 'stg_projects', ['status'], unique=False, schema='staging', postgresql_where='is_deleted = FALSE')
    op.create_table('core_citations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('cited_project_id', sa.String(length=36), nullable=False),
    sa.Column('relation_type', sa.SmallInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('project_id <> cited_project_id', name='chk_core_no_self_citation'),
    sa.ForeignKeyConstraint(['cited_project_id'], ['core.core_projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['core.core_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'cited_project_id', 'relation_type', name='uq_core_citations'),
    schema='core'
    )
    op.create_index('idx_core_citation_cited', 'core_citations', ['cited_project_id'], unique=False, schema='core')
    op.create_index('idx_core_citation_project', 'core_citations', ['project_id'], unique=False, schema='core')
    op.create_table('core_edit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('admin_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("field_name IN ('dc_title', 'dc_creator', 'dc_description', 'dc_date', 'dc_type', 'dc_language', 'dc_publisher', 'dc_contributor', 'dc_subject', 'dc_relation', 'dc_coverage', 'dc_rights', 'dc_source', 'dc_format', 'status')", name='chk_core_edit_field_valid'),
    sa.CheckConstraint("trim(reason) <> ''", name='chk_core_edit_reason_not_empty'),
    sa.ForeignKeyConstraint(['admin_id'], ['public.users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['core.core_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_index('idx_core_edit_admin', 'core_edit_logs', ['admin_id'], unique=False, schema='core')
    op.create_index('idx_core_edit_at', 'core_edit_logs', ['edited_at'], unique=False, schema='core')
    op.create_index('idx_core_edit_project', 'core_edit_logs', ['project_id'], unique=False, schema='core')
    op.create_table('core_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('stored_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('is_snapshot_file', sa.Boolean(), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('file_size > 0', name='chk_core_file_size'),
    sa.ForeignKeyConstraint(['project_id'], ['core.core_projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name'),
    schema='core'
    )
    op.create_index('idx_core_files_project', 'core_files', ['project_id'], unique=False, schema='core')
    op.create_index('idx_core_files_snapshot', 'core_files', ['project_id'], unique=False, schema='core', postgresql_where='is_snapshot_file = TRUE')
    op.create_table('core_keywords',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('language', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['core.core_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('core_research_authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['public.authors.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['core.core_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='core'
    )
    op.create_table('stg_field_comments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("field_name IN ('dc_title', 'dc_creator', 'dc_description', 'dc_date', 'dc_type', 'dc_language', 'dc_publisher', 'dc_contributor', 'dc_subject', 'dc_relation', 'dc_coverage', 'dc_rights', 'dc_source', 'dc_format')", name='chk_stg_field_name_valid'),
    sa.CheckConstraint('is_resolved = FALSE OR resolved_at IS NOT NULL', name='chk_stg_field_comment_resolved'),
    sa.ForeignKeyConstraint(['project_id'], ['staging.stg_projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('stg_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('original_name', sa.String(length=500), nullable=False),
    sa.Column('stored_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('mime_type', sa.String(length=127), nullable=False),
    sa.Column('uploaded_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('file_size > 0', name='chk_stg_file_size_positive'),
    sa.CheckConstraint('is_deleted = FALSE OR deleted_at IS NOT NULL', name='chk_stg_file_deleted_at'),
    sa.ForeignKeyConstraint(['project_id'], ['staging.stg_projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name'),
    schema='staging'
    )
    op.create_index('idx_stg_files_project', 'stg_files', ['project_id'], unique=False, schema='staging', postgresql_where='is_deleted = FALSE')
    op.create_table('stg_keywords',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=100), nullable=False),
    sa.Column('language', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['staging.stg_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('stg_research_authors',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.SmallInteger(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['public.authors.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['staging.stg_projects.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_table('stg_reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('reviewer_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['staging.stg_projects.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['public.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='staging'
    )
    op.create_index('idx_stg_reviews_project', 'stg_reviews', ['project_id'], unique=False, schema='staging')
    op.create_index('idx_stg_reviews_reviewer', 'stg_reviews', ['reviewer_id'], unique=False, schema='staging')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_stg_reviews_reviewer', table_name='stg_reviews', schema='staging')
    op.drop_index('idx_stg_reviews_project', table_name='stg_reviews', schema='staging')
    op.drop_table('stg_reviews', schema='staging')
    op.drop_table('stg_research_authors', schema='staging')
    op.drop_table('stg_keywords', schema='staging')
    op.drop_index('idx_stg_files_project', table_name='stg_files', schema='staging', postgresql_where='is_deleted = FALSE')
    op.drop_table('stg_files', schema='staging')
    op.drop_table('stg_field_comments', schema='staging')
    op.drop_table('core_research_authors', schema='core')
    op.drop_table('core_keywords', schema='core')
    op.drop_index('idx_core_files_snapshot', table_name='core_files', schema='core', postgresql_where='is_snapshot_file = TRUE')
    op.drop_index('idx_core_files_project', table_name='core_files', schema='core')
    op.drop_table('core_files', schema='core')
    op.drop_index('idx_core_edit_project', table_name='core_edit_logs', schema='core')
    op.drop_index('idx_core_edit_at', table_name='core_edit_logs', schema='core')
    op.drop_index('idx_core_edit_admin', table_name='core_edit_logs', schema='core')
    op.drop_table('core_edit_logs', schema='core')
    op.drop_index('idx_core_citation_project', table_name='core_citations', schema='core')
    op.drop_index('idx_core_citation_cited', table_name='core_citations', schema='core')
    op.drop_table('core_citations', schema='core')
    op.drop_index('idx_stg_status', table_name='stg_projects', schema='staging', postgresql_where='is_deleted = FALSE')
    op.drop_index('idx_stg_owner', table_name='stg_projects', schema='staging', postgresql_where='is_deleted = FALSE')
    op.drop_index('idx_stg_identifier', table_name='stg_projects', schema='staging')
    op.drop_index('idx_stg_fts', table_name='stg_projects', schema='staging', postgresql_using='gin')
    op.drop_table('stg_projects', schema='staging')
    op.drop_index('idx_refresh_tokens_active', table_name='refresh_tokens', schema='public', postgresql_where='revoked_at IS NULL')
    op.drop_table('refresh_tokens', schema='public')
    op.drop_index('idx_login_user', table_name='login_logs', schema='log')
    op.drop_index('idx_login_created_at', table_name='login_logs', schema='log')
    op.drop_table('login_logs', schema='log')
    op.drop_index('idx_audit_user', table_name='audit_logs', schema='log')
    op.drop_index('idx_audit_entity', table_name='audit_logs', schema='log')
    op.drop_index('idx_audit_created_at', table_name='audit_logs', schema='log')
    op.drop_table('audit_logs', schema='log')
    op.drop_index('idx_core_stg_id', table_name='core_projects', schema='core')
    op.drop_index('idx_core_status', table_name='core_projects', schema='core')
    op.drop_index('idx_core_snapshot', table_name='core_projects', schema='core', postgresql_using='gin')
    op.drop_index('idx_core_fts', table_name='core_projects', schema='core', postgresql_using='gin', postgresql_where='status = 1')
    op.drop_index('idx_core_approved_at', table_name='core_projects', schema='core')
    op.drop_table('core_projects', schema='core')
    op.drop_index('idx_users_role', table_name='users', schema='public', postgresql_where='is_deleted = FALSE')
    op.drop_index('idx_users_active_email', table_name='users', schema='public', postgresql_where='is_deleted = FALSE')
    op.drop_table('users', schema='public')
    op.drop_table('authors', schema='public')
    op.drop_table('roles', schema='public')
    op.drop_table('departments', schema='public')
    # ### end Alembic commands ###
