"""move notification to reference schema

Revision ID: e040c3f7a072
Revises: 4041de9c14d3
Create Date: 2026-06-26 02:52:42.954004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e040c3f7a072'
down_revision: Union[str, Sequence[str], None] = '4041de9c14d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('action_url', sa.String(length=500), nullable=True),
    sa.Column('sender_user_id', sa.UUID(), nullable=True),
    sa.Column('research_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['research_id'], ['staging.research_objects.staging_id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_table('user_devices',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('fcm_token', sa.Text(), nullable=False),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fcm_token'),
    schema='reference'
    )
    op.create_index(op.f('ix_reference_user_devices_user_id'), 'user_devices', ['user_id'], unique=False, schema='reference')
    op.create_table('user_notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('notification_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['reference.notifications.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='reference'
    )
    op.create_index(op.f('ix_reference_user_notifications_notification_id'), 'user_notifications', ['notification_id'], unique=False, schema='reference')
    op.create_index(op.f('ix_reference_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False, schema='reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reference_user_notifications_user_id'), table_name='user_notifications', schema='reference')
    op.drop_index(op.f('ix_reference_user_notifications_notification_id'), table_name='user_notifications', schema='reference')
    op.drop_table('user_notifications', schema='reference')
    op.drop_index(op.f('ix_reference_user_devices_user_id'), table_name='user_devices', schema='reference')
    op.drop_table('user_devices', schema='reference')
    op.drop_table('notifications', schema='reference')
    # ### end Alembic commands ###
