services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: rdms-backend

    restart: always

    ports:
      - "8000:8000"

    env_file:
      - .env.deployment

    networks:
      - rdms-network


networks:
  rdms-network:
    external: true
    name: rdms-network